import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.scss';
import Header from './components/Header/Header'; 
import Footer from './components/Footer/Footer'; 
import React, { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} layout-body`}>
        <Header />
        <main className="layout-main">
          <div className="main-container">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;